### ISSUE TITLE
Create Story Service that interacts with Dynamo and S3

### ISSUE THREAD

**Issue by bpmweel** [RECEIPT-H2020/TerriaMap#101]
The story is stored over at least 2 different systems: DynamoDB and S3.

Currently we have at least 4 components making separate calls to these systems. Meaning if anything changes we need to update all of them.

We should create a Story Service Component that interfaces with the backend that the frontent components can use as a middleware

**Comment by Maartenvm** [comment]
Duplicate and better explained in #100
