### ISSUE TITLE
Fill the 'example story' with the content from the Soy story.

### ISSUE THREAD

**Issue by Maartenvm** [RECEIPT-H2020/TerriaMap#102]
Make sure the content from the Soy story JSON gets added into the database with story ID 0.

**Comment by pushpanjalip** [comment]
Find few things while adding example story content for Soy

- We have short description & description fields for story in database but in viewer we are only using short description .
<img width="462" height="300" alt="Screenshot 2021-09-01 at 15 48 14" src="https://user-images.githubusercontent.com/21329772/131683228-da70af07-382f-46e9-800e-20054c1db98f.png">

- May be we should enable adding lat, long directly as a hotspot position
- We are also adding section for pages but not exactly using them in viewer
- In story builder we are adding ssps per page so we need to think about how to display pages with ssps in viewer
- Some bugs are found (added in backlog as issues) also working on resolving them

1. Deleting pages is not working properly . 
2. Adding default page content is not working properly.

**Comment by goord** [comment]
This issue is no longer relevant
