### ISSUE TITLE
Story Builder Size

### ISSUE THREAD

**Issue by bpmweel** [RECEIPT-H2020/TerriaMap#106]
## User story

As a  Story Editor
I want to be able to enlarge the editor panel
So that I can focus on the text I'm writing

### Proposed work
- Currently the editor is roughly 1/3rd of the screen, but while inputting text this means the actual area to write text in is quite small. It would be good to increase the size of the editor to like 50% and even add the ability to make it full width and hide the map.

**Comment by goord** [comment]
It has been enlarged, won't invest more time into this
