### ISSUE TITLE
Zoom/home camera broken

### ISSUE THREAD

**Issue by goord** [RECEIPT-H2020/TerriaMap#112]
Possibly due to the scenario button refactoring, zooming on the map seems to be broken. Also the home camera resets the view to an incorrect position

**Comment by kretep** [comment]
@goord could you clarify these points?
* With zooming, do you mean interactive zooming using the scroll wheel?
* What do you mean with the home camera? The camera position stored in the story pages?
* In which version or branch is this not working? Could you provide the / an example story or see whether this is also not working for the default story?

**Comment by goord** [comment]
Hi @kretep with zooming I mean the camera position when going to a new page. I am running the receipt branch locally. The problem can be observed in the soy test storyline, when I progress to the 'drivers of degradation' page, the camera remains focused on Europe (see image). 
![2022-06-16 09 42 27 localhost bfcb0bc1eff4](https://user-images.githubusercontent.com/5041758/174018844-1411e729-de12-4a4a-b450-5dbb8878a17a.png)
When I manually set my focus to argentina and click 'reset zoom' (top right navigation button in map), the focus switches back to Europe.

**Comment by Maartenvm** [comment]
I think I see where this bug comes from, working on it.

**Comment by goord** [comment]
Almost fixed: in the new version the view returns to the json-defined zoom level when changing scenarios, which is undesirable. Typically a user wants to zoom into a region to observe the difference between scenarios and this resetting to the default makes that a lot harder.

I reopen the issue because the above behavior seems a side-effect of the fix.

**Comment by kretep** [comment]
@goord I pushed some changes to fix this (storylines branches in both repos). It now doesn't reset the zoom when switching between scenarios, as long as `"zoomOnEnable": false` in the story initfile.

**Comment by goord** [comment]
Indeed fixed.
