### ISSUE TITLE
Story chapters in wide top navigation bar

### ISSUE THREAD

**Issue by goord** [RECEIPT-H2020/TerriaMap#113]
Feedback from some consortium members/storyline developers: the story sections could be spanning the full screen in a top navigation bar/div to give the stories more structure and take away less vertical space in the story panel. This would also allow the sections to be listed on a single line.

On the left hand side, a drop-down menu with the available stories would also make navigation between stories more feasible.

So as a starter for this: create a top navigation bar with the sections and see what it looks like.

**Comment by sjvrijn** [comment]
closed by RECEIPT-H2020/terriajs#97
