### ISSUE TITLE
Scenario buttons not working for geojson vector layers

### ISSUE THREAD

**Issue by goord** [RECEIPT-H2020/TerriaMap#114]
I implemented map scenarios using geojson catalog items in the same way I did with rasterized layers (e.g. wms) but the map does not seem to update when I click the buttons: all layers are always displayed.

To reproduce, create 2 simple geojson layers in e.g. geojson.io, put the files in test story data directory and make 2 geojson shared catalog items. Then add these layers to some mapScenarios and observe that the buttons have no effect on the visibility of the layers.

**Comment by kretep** [comment]
What does your initfile look like? Do you have an example (a branch maybe) with this specific example?

**Comment by goord** [comment]
No worries, this problem has miraculously solved itself!
