### ISSUE TITLE
All scenario maps shown initially

### ISSUE THREAD

**Issue by goord** [RECEIPT-H2020/TerriaMap#115]
When entering a story page with multiple mapScenarios, all maps + legends are initially shown, although in the story panel only the first scenario is selected (see e.g. [this example](https://user-images.githubusercontent.com/5041758/174018844-1411e729-de12-4a4a-b450-5dbb8878a17a.png). After clicking one of the scenarios everything becomes consistent, it's an initial value issue.

**Comment by goord** [comment]
Fixed by @Maartenvm

**Comment by Maartenvm** [comment]
consolidated in #126
