### ISSUE TITLE
When exiting a story, the maps for that story kept loaded

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#117]
**Describe the bug**

**To Reproduce**
- open a story and then close it
- you will see 

The button for showing the legends still is there because the maps are loaded and in this case they contain legends

![image](https://user-images.githubusercontent.com/4195550/187503606-61adfaed-ab6d-4a44-8277-05d8d33e3cf0.png)
![image](https://user-images.githubusercontent.com/4195550/187503848-e52a2fcc-c057-4b83-8ffc-c264ecb8bb52.png)

**Expected behavior**
- Clean up the map

**Comment by Maartenvm** [comment]
consolidated in #126
