### ISSUE TITLE
Redesign of Section/Page indicators

### ISSUE THREAD

**Issue by Maartenvm** [RECEIPT-H2020/TerriaMap#128]
Change the section/page indicators to

![Image](https://user-images.githubusercontent.com/1705817/198292196-d91cf067-dd06-47c1-837f-669c0f1212e0.png)

**Comment by sjvrijn** [comment]
A first draft for this can be found in the [terriajs/navigation-update](https://github.com/RECEIPT-H2020/terriajs/tree/navigation-update) branch. Only remaining problem is to get both the 'button' div and arrow polygons to highlight at the same time, but my attempts at adding a parent div with `hover:` properties to inherit, didn't work.

See below:
![Screenshot 2022-12-15 102054](https://user-images.githubusercontent.com/8833517/207822424-bc3d44b3-d32e-4d57-9638-1a6803aabe34.png)

**Comment by sjvrijn** [comment]
closed by RECEIPT-H2020/terriajs#97
