### ISSUE TITLE
Pull request #123 side effects

### ISSUE THREAD

**Issue by goord** [RECEIPT-H2020/TerriaMap#133]
There are two side effects that arose from merging the 'storylines-gijs' branch back onthe the receipt branch:

- [ ] <s>The colored dots at the bottom do not get a 'highlight' color anymore; this has a somewhat lower priority because we are planning to get rid of these soon anyway.</s>
- [ ] The map resets its zoom level upon changing a scenario with a button. This is unwanted behavior as it prevents users from inspecting scenarios at a zoomed-in location.

**Comment by sjvrijn** [comment]
The first point is obsolete since the redesign
The second is fixed by https://github.com/RECEIPT-H2020/terriajs/pull/99
