### ISSUE TITLE
Move navigation to full-width header/footer bars

### ISSUE THREAD

**Issue by sjvrijn** [RECEIPT-H2020/TerriaMap#135]
Rough draft made during discussion with @goord :

![Image](https://user-images.githubusercontent.com/8833517/208649162-d91ff57a-57b9-4c5b-9b45-9d9356107147.png)

**Comment by sjvrijn** [comment]
The new navigation bar/header has been added so far in branch [navigation-topbar](https://github.com/RECEIPT-H2020/terriajs/tree/navigation-topbar). The bottom bar/footer is also in there, but only for the story pages. I've also not been able to get the height scaling working yet.

Whether the bottom bar/footer is actually needed is currently up in the air. @goord suggested incorporating the previous/next buttons into the header bar, but I couldn't come up with a nice way to do so. Maybe those prev/next buttons could still stay at the bottom of the story panel? To be continued...

**Comment by goord** [comment]
This is excellent work, thanks. Have a good Christmas break and let's discuss in the new year what the most logical choice is

**Comment by sjvrijn** [comment]
closed by RECEIPT-H2020/terriajs#97
