### ISSUE TITLE
Select the hotspot location

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#55]
## User story
As an editor
I want to be able to click on the map
So that I can select the position of the hotspot

## Proposed work
- [x] Every time the map is clicked, mode the hotspot location
- [x] Indicate when are changes (maybe by highlighting the save button?)
- [x] Show a marker on the map

## Acceptance Criteria
- [x] Persist the changes

## Designs
![image](https://user-images.githubusercontent.com/4195550/115026742-231f5780-9ec3-11eb-984c-196213447be1.png)

**Comment by kretep** [comment]
Changes so far at https://github.com/RECEIPT-H2020/terriajs/commit/e1f9e2400f4daa56acd628d05caa8a4c127a2dc4

**Comment by pushpanjalip** [comment]
@kretep  I have made some changes to feature/story-editor-hotspot-marker & now hotspot is visible.
But still it just shows marker but does not affect geojson for specific sector.

Quetions to be discussed next sprint:

- [ ] Changing hard coded sectors?
- [ ] If there can be more than 1 sector for specific story then how can we store hotspot for sectors. In current implementation we have sector specific hotspots & geojson.  Refer to TerriaMap/wwwroot/public/json/hotspots
- [ ] Do we actually need to change geojson when hotspot location is selected?

**Comment by kretep** [comment]
"Updating the geojson" or " persisting the changes" is now captured in #92 and #93

**Comment by goord** [comment]
No we have no indication from stakeholders that sectors should be dynamic or storylines could be part of multiple sectors. Let's not overcomplicate things.
