### ISSUE TITLE
Login with Microsoft

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#64]
## User story
As an editor,
I want to login with my Microsoft account
So that I work on my stories

## Proposed work
- Use AWS Amplify (and research the possibilities, proposed something different if you find issues or complications)

## Acceptance Criteria
- Access to a login page from **www.climateimpactstories.eu/builder**
- [ ] Be able to login with email and password

## Designs
![image](https://user-images.githubusercontent.com/4195550/115022075-2adbfd80-9ebd-11eb-9d1e-78cfb9817c32.png)

**Comment by Maartenvm** [comment]
Amplify does not provide this option, and we're not switching.
