### ISSUE TITLE
Learn the possibilities of AWS Amplify

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#71]
Take a look at the features of AWS Amplify and get all-around knowledge to see how it fits in the project
https://docs.amplify.aws/

- Understand what services are included and not.
- An overall view of authentication.
- Databases, storage, and API interfaces.

Check the marker when you are done:
- [x] Yang
- [x] Maarten
- [x] Jesus
- [x] Berend
- [x] Pooja
- [x] Peter

**Comment by ctwhome** [comment]
Among the benefits I found with Amplify are:

*   Better tooling and integration with JS (JS libraries to connect all amplify services, including security between services)
*   It reminds me a lot of the Firebase ecosystem where all needed parts are working in conjunction.
*   Admin UI contains lots of out-of-the-box backend services we need for our platform. 
*   We can use the NoSQL database (DynamoDB) to persist client-side information
*   The services I am more interested in are: hosting, storage(S3), security and user management with auth login (cognito+js templates), DynamoDB, cloud functions to fire up external APIs or cron jobs(Lambda), Content management with a WYSIWYG editor. 
*   Pricing: probably free for all the project needs included in the free tier.

**Comment by Maartenvm** [comment]
This looks like it's an easy to follow tutorial

https://www.youtube.com/watch?v=g4qKydnd0vU&t=11s

________________________________
