### ISSUE TITLE
Outsider user story

### ISSUE THREAD

**Issue by anonvmvs** [RECEIPT-H2020/TerriaMap#72]
## User story

As a anonymus user
I want to create a user story
So that I can add my take on all this.

### Proposed work

- 

### Acceptance Criteria

* [ ] 
* [ ] Update documentation

**Comment by Maartenvm** [comment]
So that works

**Comment by ctwhome** [comment]
I guess this is the normal behavior of adding issues to a repo. The PO should include in the issue (private or public) project backlog if needed
