### ISSUE TITLE
Review AWS files in Repo

### ISSUE THREAD

**Issue by bpmweel** [RECEIPT-H2020/TerriaMap#75]
There are a number of AWS generated files in the repository, we should double check whether they should be there and /or whether we are missing some.

We should consult with Farook as he has experience with this.

**Comment by kretep** [comment]
It looks like our setup is largely correct, with the exception of one file. I basically had a look at this page: https://docs.amplify.aws/cli/reference/files

Most files are correctly added to git or ignored, with the exception of team-provider-info.json, see https://docs.amplify.aws/cli/reference/files#team-provider-infojson

I guess we need the file to collaborate and it's not a security risk as you still need your credentials to push, I guess it's just cleaner to not have it version controlled.

Here's the commits to remove the file, somehow I still cannot create a PR:
https://github.com/RECEIPT-H2020/terriajs/tree/amplify-review-files
