### ISSUE TITLE
Not possible to verify email account

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#78]
When registering an account, the email I get in the mailbox with the link has the following issues: 

- It redirects to a no-secure URL that never ends loading. 

![image](https://user-images.githubusercontent.com/4195550/116548386-6b436e80-a8f4-11eb-9d08-ed43f6c6e9ff.png)

**Comment by sjvrijn** [comment]
In the user pool under 'Sign-up experience' I've checked the box for

> Allow Cognito to automatically send messages to verify and confirm - Recommended

This now sends a simple email with a verification code that I could use to register a new account for the builder.

(Unless this issue was not about account registration for the builder?)

**Comment by kretep** [comment]
@sjvrijn sounds like a fix to me :) I'm not sure how the original account creation was set up (I guess it worked at some point), but if you have it working, then we can consider it fixed
