### ISSUE TITLE
Implement Continuous Integration

### ISSUE THREAD

**Issue by Maartenvm** [RECEIPT-H2020/TerriaMap#86]
## User story
As a developer 
I want to make sure that if I push any changes to the code, nothing else breaks that I did not foresee, and the application still builds correctly. In order to start this process, we need Continuous Integration.

## Proposed work
- [x] Implement a CI with github actions

## Acceptance Criteria
- [x] The application builds correctly on pushing code.

**Comment by bpmweel** [comment]
Application build is done with https://github.com/RECEIPT-H2020/TerriaMap/pull/94 and https://github.com/RECEIPT-H2020/terriajs/pull/71

**Comment by goord** [comment]
With a few months left for development, this is no longer worthwile
